spring:
  application:
    name: feign-consumer
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      register-with-eureka: false
  instance:
    prefer-ip-address: true
feign:
  circuitbreaker:
        enable: true